workflows:
  react-native-android:
    name: LinkLayer Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.linklayer.app"
        EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID: $WALLETCONNECT_PROJECT_ID
      node: 18.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          npx expo run:android --variant release
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@linklayer.com
        notify:
          success: true
          failure: false

  react-native-ios:
    name: LinkLayer iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.linklayer.app
      groups:
        - app_store
      vars:
        BUNDLE_ID: "com.linklayer.app"
        EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID: $WALLETCONNECT_PROJECT_ID
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS IPA
        script: |
          npx expo run:ios --configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false
      email:
        recipients:
          - user@linklayer.com
        notify:
          success: true
          failure: false
