workflows:
  react-native-android:
    name: PEPULink Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.jwgray1010.pepulink"
        EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID: $WALLETCONNECT_PROJECT_ID
        EXPO_PUBLIC_API_KEY: $PEPU_API_KEY
        EXPO_PUBLIC_PEPU_TOKEN_ADDRESS: "0xdb0976d5edc9bd329d354dabdeae00e4de11c941"
        EXPO_PUBLIC_WPEPU_TOKEN_ADDRESS: "0xf9cf4a16d26979b929be7176bac4e7084975fcb8"
        EXPO_PUBLIC_PEPU_POOL_ADDRESS: "0x3a614c79a17b18819ba6b97e330b61ba8fe34435"
        EXPO_PUBLIC_PEPU_WALLET_ADDRESS: "0x919d918E23456ed8472AfBf17984f8f458661bCF"
        EXPO_PUBLIC_PEPU_RPC_URL: "https://rpc-pepu-v2-mainnet-0.t.conduit.xyz"
        EXPO_PUBLIC_PEPU_CHAIN_ID: "97741"
        EXPO_PUBLIC_PEPU_EXPLORER_URL: "https://explorer-pepu-v2-mainnet-0.t.conduit.xyz"
        EXPO_PUBLIC_APP_NAME: "PEPULink"
        EXPO_PUBLIC_APP_VERSION: "2.0.0"
      node: 18.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android APK
        script: |
          npx expo run:android --variant release
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user@linklayer.com
        notify:
          success: true
          failure: false

  react-native-ios:
    name: PEPULink iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.jwgray1010.pepulink
      groups:
        - app_store
      vars:
        BUNDLE_ID: "com.jwgray1010.pepulink"
        EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID: $WALLETCONNECT_PROJECT_ID
        EXPO_PUBLIC_API_KEY: $PEPU_API_KEY
        EXPO_PUBLIC_PEPU_TOKEN_ADDRESS: "0xdb0976d5edc9bd329d354dabdeae00e4de11c941"
        EXPO_PUBLIC_WPEPU_TOKEN_ADDRESS: "0xf9cf4a16d26979b929be7176bac4e7084975fcb8"
        EXPO_PUBLIC_PEPU_POOL_ADDRESS: "0x3a614c79a17b18819ba6b97e330b61ba8fe34435"
        EXPO_PUBLIC_PEPU_WALLET_ADDRESS: "0x919d918E23456ed8472AfBf17984f8f458661bCF"
        EXPO_PUBLIC_PEPU_RPC_URL: "https://rpc-pepu-v2-mainnet-0.t.conduit.xyz"
        EXPO_PUBLIC_PEPU_CHAIN_ID: "97741"
        EXPO_PUBLIC_PEPU_EXPLORER_URL: "https://explorer-pepu-v2-mainnet-0.t.conduit.xyz"
        EXPO_PUBLIC_APP_NAME: "PEPULink"
        EXPO_PUBLIC_APP_VERSION: "2.0.0"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS IPA
        script: |
          npx expo run:ios --configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false
      email:
        recipients:
          - user@linklayer.com
        notify:
          success: true
          failure: false
        notify:
          success: true
          failure: false
