name: LinkLayer CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint || echo "No lint script found"
    
    - name: Run tests
      run: npm test || echo "No test script found"
    
    - name: Check Expo configuration
      run: npx expo-doctor || echo "Expo doctor completed with warnings"

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.17.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for web
      run: npx expo export:web
      env:
        EXPO_PUBLIC_WALLETCONNECT_PROJECT_ID: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
        EXPO_PUBLIC_LINKLAYER_RPC_URL: https://rpc-linklayer-v2-mainnet-0.t.conduit.xyz
        EXPO_PUBLIC_LINKLAYER_CHAIN_ID: 97741

  codemagic-trigger:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger Codemagic build
      run: |
        echo "Main branch updated - Codemagic will automatically trigger builds"
        echo "iOS and Android builds will be handled by Codemagic CI/CD"
